FROM arm32v7/python:3.7-buster

WORKDIR /app

RUN apt-get update -y
RUN apt install gcc -y

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]